modified:   Dockerfile

diff --git a/sparkdev-toree/Dockerfile b/sparkdev-toree/Dockerfile
--- a/sparkdev-toree/Dockerfile
+++ b/sparkdev-toree/Dockerfile
@@ -1,12 +1,13 @@
 FROM gettyimages/spark:2.4.1-hadoop-3.0
 MAINTAINER "Israel Zúñiga de la Mora https://github.com/israelzuniga/turbo-adventure"
 
-USER root
 
 
 # install git
 RUN set -ex && \
-    apt-get update && apt-get install -y --no-install-recommends git
+    apt-get update && apt-get install -y --no-install-recommends git \
+    g++ libc6-dev wget;
+
 
 
 # for declarativewidgets
@@ -24,32 +25,67 @@ ENV PYTHONPATH $SPARK_HOME/python:$SPARK_HOME/python/lib/py4j-0.10.7-src.zip
 ENV PYSPARK_PYTHON /usr/bin/python
 
 
-# Toree
+# Jupyter
+#
+RUN python3 -m pip install --no-cache-dir "jupyter==${JUPYTER_VERSION}" "tornado<6" toree; \
+    jupyter --version; \
+    # Set the right Python version for Spark worker under PySpark
+    apt-get install -y --no-install-recommends jq; \
+    PYTHON3_KERNEL_CONF="/usr/local/share/jupyter/kernels/python3/kernel.json"; \
+    cat "${PYTHON3_KERNEL_CONF}" \
+        | jq --argjson env '{ "PYSPARK_PYTHON": "python3" }' '. + {env: $env}' \
+        > "${PYTHON3_KERNEL_CONF}.tmp"; \
+    mv "${PYTHON3_KERNEL_CONF}.tmp" "${PYTHON3_KERNEL_CONF}"; \
+    PYTHON2_KERNEL_CONF="/usr/local/share/jupyter/kernels/python2/kernel.json"; \
+    cat "${PYTHON2_KERNEL_CONF}" \
+        | jq --argjson env '{ "PYSPARK_PYTHON": "python2" }' '. + {env: $env}' \
+        > "${PYTHON2_KERNEL_CONF}.tmp"; \
+    mv "${PYTHON2_KERNEL_CONF}.tmp" "${PYTHON2_KERNEL_CONF}"; \
+    apt-get remove -y jq; \
+    #
+    # Toree
+    #
+    jupyter toree install --spark_home=${SPARK_HOME}; \
+    #
+    # gosu installation (https://github.com/tianon/gosu#installation)
+    #
+    dpkgArch="$(dpkg --print-architecture | awk -F- '{ print $NF }')"; \
+    wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/${GOSU_VERSION}/gosu-$dpkgArch"; \
+    wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/${GOSU_VERSION}/gosu-$dpkgArch.asc"; \
+    # Verify the signature
+    GNUPGHOME="$(mktemp -d)"; \
+    apt-get install -y --no-install-recommends gnupg2 dirmngr; \
+    # Skip the verification step for now, the keyserver is very buggy
+    # For flaky keyservers, consider https://github.com/tianon/pgp-happy-eyeballs, ala https://github.com/docker-library/php/pull/666
+    # count=0; \
+    # until (gpg2 --batch --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4) || ((count++ >= 10)); do \
+        # echo "Cannot contact keyserver, trying again..." \
+    # done; \
+    # gpg2 --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu; \
+    # command -v gpgconf && gpgconf --kill all || :; \
+    rm -rf "${GNUPGHOME}" /usr/local/bin/gosu.asc; \
+    # Clean up fetch dependencies
+    chmod +x /usr/local/bin/gosu; \
+    # Verify that the binary works
+    gosu --version; \
+    gosu nobody true; \
+    apt-get remove -y gnupg2 dirmngr; \
+    #
+    # Remove unnecessary build-time only dependencies
+    #
+    apt-get remove -y wget; \
+    rm -rf /var/lib/apt/lists/*
 
-# get to the latest jupyter release and necessary libraries
-RUN pip install jupyter seaborn futures && \
-    pip install seaborn futures && \
-    pip install futures
-
-ENV DECL_WIDGETS_VERSION 0.4.3
-
-# install incubator extensions
-RUN pip install jupyter_dashboards \
-    jupyter_declarativewidgets \
-    jupyter_dashboards_bundlers
-RUN jupyter dashboards quick-setup
-# RUN jupyter declarativewidgets quick-setup
-RUN jupyter nbextension enable jupyter_dashboards --py
-# RUN jupyter declarativewidgets activate
-# RUN jupyter nbextension enable dashboards_bundlers --py
-
-
-# install Toree
-RUN pip install toree
-RUN jupyter toree install --user
 
 EXPOSE 8888 8080 4040 4041 4042 4043 4044
 
 
 # include nice intro notebook
 # COPY index.ipynb $HOME/notebooks/
+
+
+
+# ENV NOTEBOOKS_DIR "/notebooks/"
+
+COPY run.sh /
+CMD ["bash /run.sh"]
